name: siraj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.15.0
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  adhan: ^2.0.0+1
  http: ^1.6.0
  audioplayers: ^6.8.0
  go_router: ^17.3.0
  geolocator: ^14.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/data/
    - assets/images/

  fonts:
    - family: UthmanTNB
      fonts:
        - asset: assets/fonts/UthmanTNB_v2-0.ttf
    - family: QuranFont
      fonts:
        - asset: assets/fonts/QuranFont.ttf
