import json

# الدفعة 1: الأبواب 27,28,1,6,7,8,9,10,11,12,13,14,15,2,3,4,5,16-26,29-35
T = {
'27': {'en':'Morning & Evening','ur':'صبح و شام کے اذکار','fa':'اذکار صبح و شام','id':'Zikir Pagi & Petang','tr':'Sabah & Akşam Zikirleri','fr':'Invocations du matin et du soir','bn':'সকাল-সন্ধ্র জিকির','ms':'Zikir Pagi & Petang','ha':'Azkar na Safe da Yamma','sw':'Adhkari za Asubuhi na Jioni','de':'Morgen- & Abendgebete','ru':'Утренние и вечерние поминания','zh':'早晚的记念','es':'Súplicas de la mañana y la tarde'},
'28': {'en':'Before Sleeping','ur':'سونے کے اذکار','fa':'اذکار خواب','id':'Zikir Sebelum Tidur','tr':'Uyku Zikirleri','fr':'Invocations du coucher','bn':'ঘুমের জিকির','ms':'Zikir Tidur','ha':'Azkar na Barci','sw':'Adhkari za Kulala','de':'Gebete vor dem Schlafen','ru':'Поминания перед сном','zh':'睡前的记念','es':'Súplicas al dormir'},
'1': {'en':'Upon Waking','ur':'بیدار ہونے کی دعا','fa':'دعای بیداری','id':'Doa Bangun Tidur','tr':'Uyanınca Okunan Dua','fr':'Invocation au réveil','bn':'ঘুম থেকে জাগার দোয','ms':'Doa Bangun Tidur','ha':"Addu'ar Farkawa",'sw':'Dua ya Kuamka','de':'Bittgebet beim Erwachen','ru':'Мольба при пробуждении','zh':'睡醒时的祈祷','es':'Súplica al despertar'},
'6': {'en':'Entering the Toilet','ur':'بیت الخلاء میں داخل ہونے کی دعا','fa':'دعای ورود به دستشویی','id':'Doa Masuk WC','tr':'Tuvalete Girerken Dua','fr':'Invocation pour entrer aux toilettes','bn':'শৌচাগার প্রবেশের দোয়া','ms':'Doa Masuk Tandas','ha':"Addu'ar Shiga Bayan Gida",'sw':'Dua ya Kuingia Chooni','de':'Bittgebet beim Betreten der Toilette','ru':'Мольба при входе в туалет','zh':'入厕的祈祷','es':'Súplica al entrar al baño'},
'7': {'en':'Leaving the Toilet','ur':'بیت الخلاء سے نکلنے کی دعا','fa':'دعای خروج از دستشویی','id':'Doa Keluar WC','tr':'Tuvaletten Çıkınca Dua','fr':'Invocation en sortant des toilettes','bn':'শচাগার থেকে বের হওয়ার দোয়া','ms':'Doa Keluar Tandas','ha':"Addu'ar Fita Bayan Gida",'sw':'Dua ya Kutoka Chooni','de':'Bittgebet beim Verlassen der Toilette','ru':'Мольба при выходе из туалета','zh':'出厕的祈祷','es':'Súplica al salir del baño'},
'8': {'en':'Before Ablution','ur':'وضو سے پہلے کا ذکر','fa':'ذکر قبل از وضو','id':'Zikir Sebelum Wudhu','tr':'Abdestten Önce Zikir','fr':'Invocation avant les ablutions','bn':'অজুর আগের জিকির','ms':'Zikir Sebelum Wuduk','ha':'Zikiri Kafin Alwala','sw':'Dhikr Kabla ya Udhu','de':'Vor der Waschung','ru':'Перед омовением','zh':'小净前的记念','es':'Antes de la ablución'},
'9': {'en':'After Ablution','ur':'وضو کے بعد کا ذکر','fa':'ذکر بعد از وضو','id':'Zikir Setelah Wudhu','tr':'Abdestten Sonra Zikir','fr':'Invocation après les ablutions','bn':'অজুর পরের জিকির','ms':'Zikir Selepas Wuduk','ha':'Zikiri Bayan Alwala','sw':'Dhikr Baada ya Udhu','de':'Nach der Waschung','ru':'После омовения','zh':'小净后的记念','es':'Después de la ablución'},
'10': {'en':'Leaving Home','ur':'گھر سے نکلنے کا ذکر','fa':'ذکر خروج از منزل','id':'Zikir Keluar Rumah','tr':'Evden Çıkarken Zikir','fr':'Invocation en quittant la maison','bn':'ঘর থেকে বর হওয়ার জিকির','ms':'Zikir Keluar Rumah','ha':'Zikiri Fita Gida','sw':'Dhikr ya Kutoka Nyumbani','de':'Beim Verlassen des Hauses','ru':'При выходе из дома','zh':'出门的记念','es':'Al salir de casa'},
'11': {'en':'Entering Home','ur':'گھر میں داخل ہونے کا ذکر','fa':'ذکر ورود به منزل','id':'Zikir Masuk Rumah','tr':'Eve Girerken Zikir','fr':'Invocation en entrant chez soi','bn':'ঘরে প্রবেশের জিকির','ms':'Zikir Masuk Rumah','ha':'Zikiri Shiga Gida','sw':'Dhikr ya Kuingia Nyumbani','de':'Beim Betreten des Hauses','ru':'При входе в дом','zh':'进门的记念','es':'Al entrar a casa'},
'12': {'en':'Going to the Mosque','ur':'مسجد جانے کی دعا','fa':'دعای رفتن به مسجد','id':'Doa Pergi ke Masjid','tr':'Camiye Giderken Dua','fr':'Invocation en allant à la mosquée','bn':'মসজিদে যাওয়ার দোয়া','ms':'Doa Pergi ke Masjid','ha':"Addu'ar Zuwa Masallaci",'sw':'Dua ya Kwenda Msikitini','de':'Auf dem Weg zur Moschee','ru':'По пути в мечеть','zh':'前往清真寺的祈祷','es':'Al ir a la mezquita'},
'13': {'en':'Entering the Mosque','ur':'مسجد میں داخل ہونے کی دعا','fa':'دعای ورود به مسجد','id':'Doa Masuk Masjid','tr':'Camiye Girerken Dua','fr':'Invocation pour entrer à la mosquée','bn':'মসজিদে প্রবেশের দোয়া','ms':'Doa Masuk Masjid','ha':"Addu'ar Shiga Masallaci",'sw':'Dua ya Kuingia Msikitini','de':'Beim Betreten der Moschee','ru':'При входе в мечеть','zh':'进入清真寺的祈祷','es':'Al entrar a la mezquita'},
'14': {'en':'Leaving the Mosque','ur':'مسجد سے نکلنے کی دعا','fa':'دعای خروج از مسجد','id':'Doa Keluar Masjid','tr':'Camiden Çıkarken Dua','fr':'Invocation en sortant de la mosquée','bn':'মসজিদ থেকে বের হওয়ার দোয়া','ms':'Doa Keluar Masjid','ha':"Addu'ar Fita Masallaci",'sw':'Dua ya Kutoka Msikitini','de':'Beim Verlassen der Moschee','ru':'При выходе из мечети','zh':'离开清真寺的祈祷','es':'Al salir de la mezquita'},
'15': {'en':'Adhan (Call to Prayer)','ur':'اذان کے اذکار','fa':'اذکار اذان','id':'Zikir Azan','tr':'Ezan Zikirleri','fr':'Invocations de l\\'appel à la prière','bn':'আজানের জিকির','ms':'Zikir Azan','ha':'Azkar na Kiran Sallah','sw':'Adhkari za Adhana','de':'Gebetsruf (Adhan)','ru':'Азан (призыв к молитве)','zh':'宣礼的记念','es':'El Adhan (llamado a la oración)'},
'2': {'en':'Getting Dressed','ur':'کپڑا پہننے کی دعا','fa':'دعای پوشیدن لباس','id':'Doa Memakai Pakaian','tr':'Giyinirken Dua','fr':'Invocation en s\\'habillant','bn':'কাপড় পরার দোয়া','ms':'Doa Memakai Pakaian','ha':"Addu'ar Sanya Tufafi",'sw':'Dua ya Kuvaa Nguo','de':'Beim Anziehen','ru':'При одевании','zh':'穿衣的祈祷','es':'Al vestirse'},
'3': {'en':'Wearing New Clothes','ur':'نیا کپڑا پہننے کی دعا','fa':'دعای پوشیدن لباس نو','id':'Doa Memakai Pakaian Baru','tr':'Yeni Elbise Giyerken Dua','fr':'Invocation pour un vêtement neuf','bn':'নতুন কাপড় পরার দোয়া','ms':'Doa Memakai Pakaian Baru','ha':"Addu'ar Sanya Sabon Tufa",'sw':'Dua ya Kuvaa Nguo Mpya','de':'Beim Tragen neuer Kleidung','ru':'При надевании новой одежды','zh':'穿新衣的祈祷','es':'Al vestir ropa nueva'},
'4': {'en':'For One Wearing New Clothes','ur':'نیا کپڑا پہننے والے کے لیے دعا','fa':'دعا برای کسی که لباس نو پوشیده','id':'Doa untuk yang Memakai Pakaian Baru','tr':'Yeni Elbise Giyene Dua','fr':'Invocation pour celui qui porte un vêtement neuf','bn':'নতুন কাপড় পরিধানকারীর জন্য দোয়া','ms':'Doa untuk yang Memakai Pakaian Baru','ha':"Addu'a ga Mai Sabon Tufa",'sw':'Dua kwa Anayevaa Nguo Mpya','de':'Für jemanden in neuer Kleidung','ru':'Для надевшего новую одежду','zh':'为穿新衣者祈祷','es':'Para quien viste ropa nueva'},
'5': {'en':'When Undressing','ur':'کپڑا اتارنے کی دعا','fa':'دعای درآوردن لباس','id':'Doa Melepas Pakaian','tr':'Elbise Çıkarırken Dua','fr':'Invocation en se déshabillant','bn':'কাপড় খোলার দোয়া','ms':'Doa Menanggalkan Pakaian','ha':"Addu'ar Cire Tufa",'sw':'Dua ya Kuvua Nguo','de':'Beim Ausziehen','ru':'При снятии одежды','zh':'脱衣的祈祷','es':'Al quitarse la ropa'},
'16': {'en':'Opening Supplication (Prayer)','ur':'دعائے استفتاح','fa':'دعای استفتاح','id':'Doa Istiftah','tr':'İftitah Duası','fr':'Invocation d\\'ouverture','bn':'দোয়া ইস্তিফতাহ','ms':'Doa Istiftah','ha':"Addu'ar Buɗe Sallah",'sw':'Dua ya Kufungua Sala','de':'Eröffnungsbittgebet','ru':'Мольба открытия молитвы','zh':'礼拜开始的祈祷','es':'Súplica de apertura'},
'17': {'en':'During Bowing (Ruku)','ur':'رکوع کی دعا','fa':'دعای رکوع','id':'Doa Ruku','tr':'Rükû Duası','fr':'Invocation de l\\'inclinaison','bn':'রুকুর দোয়া','ms':'Doa Rukuk','ha':"Addu'ar Ruku'i",'sw':'Dua ya Rukuu','de':'Bittgebet der Verbeugung','ru':'Мольба поясного поклона','zh':'鞠躬时的祈祷','es':'Súplica de la inclinación'},
'18': {'en':'Rising from Bowing','ur':'رکوع سے اٹھنے کی دعا','fa':'دعای برخاستن از رکوع','id':'Doa Bangkit dari Ruku','tr':'Rükûdan Kalkınca Dua','fr':'Invocation en se relevant de l\\'inclinaison','bn':'রুকু থেকে ওঠার দোয়','ms':'Doa Bangun dari Rukuk','ha':"Addu'ar Tashi daga Ruku'i",'sw':'Dua ya Kuinuka kutoka Rukuu','de':'Beim Aufrichten aus der Verbeugung','ru':'Мольба при выпрямлении','zh':'起身时的祈祷','es':'Al levantarse de la inclinación'},
'19': {'en':'During Prostration (Sujood)','ur':'سجدے کی دعا','fa':'دعای سجده','id':'Doa Sujud','tr':'Secde Duası','fr':'Invocation de la prosternation','bn':'সিজদার দোয়া','ms':'Doa Sujud','ha':"Addu'ar Sujada",'sw':'Dua ya Sujudu','de':'Bittgebet der Niederwerfung','ru':'Мольба земного поклона','zh':'叩头时的祈祷','es':'Súplica de la postración'},
'20': {'en':'Between the Two Prostrations','ur':'دو سجدوں کے درمیان کی دعا','fa':'دعای بین دو سجده','id':'Doa Duduk di Antara Dua Sujud','tr':'İki Secde Arası Dua','fr':'Invocation entre les deux prosternations','bn':'দই সিজদার মাঝের দোয়া','ms':'Doa Antara Dua Sujud','ha':"Addu'ar Tsakanin Sujada Biyu",'sw':'Dua Baina ya Sujudu Mbili','de':'Zwischen den zwei Niederwerfungen','ru':'Между двумя земными поклонами','zh':'两叩头之间的祈祷','es':'Entre las dos postraciones'},
'21': {'en':'Prostration of Recitation','ur':'سجدہ تلاوت کی دعا','fa':'دعای سجده تلاوت','id':'Doa Sujud Tilawah','tr':'Tilavet Secdesi Duası','fr':'Invocation de la prosternation de récitation','bn':'সিজদা তিলাওয়াতের দোয়া','ms':'Doa Sujud Tilawah','ha':"Addu'ar Sujadar Karatu",'sw':'Dua ya Sujudu ya Kisomo','de':'Niederwerfung der Rezitation','ru':'Земной поклон при чтении','zh':'诵读叩头的祈祷','es':'Postración de la recitación'},
'22': {'en':'Tashahhud','ur':'تشہد','fa':'تشهد','id':'Tasyahud','tr':'Tahiyyat (Teşehhüd)','fr':'At-Tashahhud','bn':'তাশাহহুদ','ms':'Tasyahud','ha':'Tashahhudi','sw':'Tashahhudi','de':'Taschahhud','ru':'Ташаххуд','zh':'作证词','es':'El Tashahhud'},
'23': {'en':'Blessings on the Prophet after Tashahhud','ur':'تشہد کے بعد درود','fa':'صلوات بر پیامبر بعد از تشهد','id':'Selawat setelah Tasyahud','tr':'Teşehhüdden Sonra Salavat','fr':'Prière sur le Prophète après le Tashahhud','bn':'তাশাহহুদের পর দরূদ','ms':'Selawat selepas Tasyahud','ha':'Salati bayan Tashahhudi','sw':'Swala kwa Nabii baada ya Tashahhudi','de':'Segensgebet nach dem Taschahhud','ru':'Салават после ташаххуда','zh':'作证词后赞念先知','es':'Bendiciones sobre el Profeta tras el Tashahhud'},
'24': {'en':'Supplication after Final Tashahhud','ur':'آخری تشہد کے بعد سلام سے پہلے دعا','fa':'دعا بعد از تشهد آخر پیش از سلام','id':'Doa setelah Tasyahud Akhir sebelum Salam','tr':'Son Teşehhüdden Sonra Selamdan Önce Dua','fr':'Invocation après le dernier Tashahhud avant le Salam','bn':'শষ তাশাহহুদের পর সালামের আগে দোয়া','ms':'Doa selepas Tasyahud Akhir sebelum Salam','ha':"Addu'a bayan Tashahhudi na Ƙarshe kafin Sallama",'sw':'Dua baada ya Tashahhudi ya Mwisho kabla ya Salamu','de':'Bittgebet nach dem letzten Taschahhud','ru':'Мольба после последнего ташаххуда','zh':'末次作证词后、说色兰前的祈祷','es':'Súplica tras el último Tashahhud antes del Salam'},
'25': {'en':'Remembrance after Prayer','ur':'نماز کے بعد کے اذکار','fa':'اذکار بعد از نماز','id':'Zikir setelah Salat','tr':'Namazdan ayer','ur':'وتر کے سلام کے بعد کا ذکر','fa':'ذکر بعد از سلام وتر','id':'Zikir setelah Salam Witir','tr':'Vitir Selamından Sonra Zikir','fr':'Invocation après le Witr','bn':'বতরের সালামের পরের জিকির','ms':'Zikir selepas Salam Witir','ha':'Zikiri bayan Sallamar Witiri','sw':'Dhikr baada ya Salamu ya Witri','de':'Nach dem Witr-Gebet','ru':'После молитвы витр','zh':'威特尔拜结束后的记念','es':'Después de la oración Witr'},
'34': {'en':'Anxiety and Sorrow','ur':'غم اور پریشانی کی دعا','fa':'دعای اندوه و غم','id':'Doa Gundah dan Sedih','tr':'Üzüntü ve Keder Duası','fr':'Invocation contre l\\'anxiété et la tristesse','bn':'দুশ্চিন্তা ও দখের দোয়া','ms':'Doa Gundah dan Sedih','ha':"Addu'ar Damuwa da Baƙin Ciki",'sw':'Dua ya Wasiwasi na Huzuni','de':'Bei Angst und Kummer','ru':'При тревоге и печали','zh':'忧虑与悲伤的祈祷','es':'Ansiedad y tristeza'},
'35': {'en':'Distress and Anguish','ur':'کرب اور تکلیف کی دعا','fa':'دعای کرب و اندوه شدید','id':'Doa Kesusahan','tr':'Sıkıntı ve Keder Duası','fr':'Invocation contre l\\'affliction','bn':'বিপদ ও কষ্টের দোয়া','ms':'Doa Kesusahan','ha':"Addu'ar Tsananin Damuwa",'sw':'Dua ya Dhiki','de':'Bei Bedrängnis','ru':'При горе и скорби','zh':'困厄的祈祷','es':'Aflicción y angustia'},
}

path = '/home/user/projects/siraj/assets/data/athkar_full.json'
data = json.load(open(path))
count = 0
for cat in data['categories']:
    if cat['id'] in T:
        cat['names'] = T[cat['id']]
        count += 1
json.dump(data, open(path,'w',encoding='utf-8'), ensure_ascii=False, indent=2)
print(f"✅ الدفعة 1: {count} باب مترجم")
