-- جدول تقارير أخطاء الترجمة: يسمح لأي مستخدم بالإبلاغ عن مشكلة في ترجمة
-- آية معيّنة بلغة معيّنة (زر "أبلغ عن خطأ ترجمة" في شاشة القراءة).
-- هذا جدول استقبال بلاغات (write-only من العميل) لا جدول محتوى معروض،
-- فسياسات RLS تسمح بالإدراج العام فقط، ولا تسمح بأي قراءة/تعديل/حذف من
-- anon - المراجعة والحل تتم من لوحة تحكم Supabase مباشرة (خدمة موثوقة)،
-- تفادياً لتكرار ثغرة RLS السابقة (جداول بلا سياسات = بلا حماية فعلية).

CREATE TABLE IF NOT EXISTS "public"."translation_reports" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "language_code" "text" NOT NULL,
    "surah_id" smallint NOT NULL REFERENCES "public"."surahs"("id"),
    "ayah_number" smallint NOT NULL,
    "reported_issue_text" "text" NOT NULL,
    "reporter_note" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "resolved" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."translation_reports" OWNER TO "postgres";

ALTER TABLE "public"."translation_reports" ENABLE ROW LEVEL SECURITY;

-- أي مستخدم (بما فيهم الضيوف) يمكنه إرسال بلاغ - لا حاجة لتسجيل دخول
-- كي لا نمنع مستخدماً حسن النية من الإبلاغ عن خطأ حقيقي.
CREATE POLICY "Public can submit reports" ON "public"."translation_reports"
    FOR INSERT WITH CHECK (true);

-- عمداً: لا سياسة SELECT/UPDATE/DELETE لـanon - البلاغات قد تحوي ملاحظة
-- حرة من المستخدم، ولا مبرر لعرضها للعامة. المراجعة عبر لوحة تحكم
-- Supabase (تتجاوز RLS بمفتاح service role).
